#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
from tensorboard.backend.event_processing import event_accumulator


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot Phase5 training/testing epoch curves for 4 methods.")
    parser.add_argument(
        "--runs_json",
        type=str,
        default="runs/phase5_fullscale_latest.json",
        help="JSON file generated by run_phase5_ablation.sh",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="docs/figures",
        help="Directory to save figures and summary",
    )
    parser.add_argument(
        "--title_prefix",
        type=str,
        default="NYUv2 V2 Full-scale Comparison",
        help="Plot title prefix",
    )
    return parser.parse_args()


def find_event_file(run_dir: Path) -> Optional[Path]:
    tb_dir = run_dir / "tensorboard"
    files = sorted(tb_dir.glob("events.out.tfevents.*"))
    return files[0] if files else None


def get_scalar_series(event_file: Path, tag: str) -> Tuple[List[int], List[float]]:
    ea = event_accumulator.EventAccumulator(str(event_file))
    ea.Reload()
    values = ea.Scalars(tag)
    if not values:
        return [], []
    steps = [int(v.step) for v in values]
    vals = [float(v.value) for v in values]
    return steps, vals


def plot_lines(data: Dict[str, Dict[str, List[float]]], key: str, ylabel: str, title: str, out_path: Path) -> None:
    plt.figure(figsize=(10, 5.5))
    for method, series in data.items():
        xs = series.get("epochs", [])
        ys = series.get(key, [])
        if xs and ys and len(xs) == len(ys):
            plt.plot(xs, ys, marker="o", markersize=3, linewidth=2, label=method)
    plt.xlabel("Epoch")
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid(alpha=0.25)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()


def plot_final_bar(data: Dict[str, Dict[str, List[float]]], out_path: Path, title: str) -> None:
    methods = []
    train_final = []
    val_final = []
    for method, series in data.items():
        if series.get("train_loss") and series.get("val_loss"):
            methods.append(method)
            train_final.append(series["train_loss"][-1])
            val_final.append(series["val_loss"][-1])

    if not methods:
        return

    x = list(range(len(methods)))
    width = 0.38
    plt.figure(figsize=(9.5, 5))
    plt.bar([i - width / 2 for i in x], train_final, width=width, label="Train final")
    plt.bar([i + width / 2 for i in x], val_final, width=width, label="Test final")
    plt.xticks(x, methods, rotation=15)
    plt.ylabel("Final Error")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()


def main() -> None:
    args = parse_args()
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    runs_json = Path(args.runs_json)
    if not runs_json.exists():
        raise FileNotFoundError(f"Run mapping JSON not found: {runs_json}")

    payload = json.loads(runs_json.read_text(encoding="utf-8"))
    run_entries = payload.get("runs", [])
    if not run_entries:
        raise RuntimeError(f"No runs found in mapping JSON: {runs_json}")

    curves: Dict[str, Dict[str, List[float]]] = {}
    rows = []
    val_metric_history: Dict[str, Dict[str, List[float]]] = {}
    for item in run_entries:
        method = item["method"]
        run_path = item["run_path"]
        run_dir = Path(run_path)
        event_file = find_event_file(run_dir)
        if event_file is None:
            print(f"[WARN] No TensorBoard event file in {run_dir}")
            continue

        train_epochs, train_losses = get_scalar_series(event_file, "epoch/train_loss")
        val_epochs, val_losses = get_scalar_series(event_file, "epoch/val_loss")
        if not train_epochs or not val_epochs:
            print(f"[WARN] Missing epoch tags in {run_dir}")
            continue

        val_rmse_epochs, val_rmse_values = get_scalar_series(event_file, "epoch/val_rmse")
        val_abs_rel_epochs, val_abs_rel_values = get_scalar_series(event_file, "epoch/val_abs_rel")

        epoch_to_train = dict(zip(train_epochs, train_losses))
        epoch_to_val = dict(zip(val_epochs, val_losses))
        common_epochs = sorted(set(epoch_to_train.keys()).intersection(epoch_to_val.keys()))
        train_common = [epoch_to_train[e] for e in common_epochs]
        val_common = [epoch_to_val[e] for e in common_epochs]
        gap_common = [v - t for v, t in zip(val_common, train_common)]

        curves[method] = {
            "epochs": common_epochs,
            "train_loss": train_common,
            "val_loss": val_common,
            "generalization_gap": gap_common,
        }

        val_metric_history[method] = {
            "run": run_dir.name,
            "epochs": common_epochs,
            "train_loss": train_common,
            "val_loss": val_common,
            "generalization_gap": gap_common,
            "val_rmse_epochs": val_rmse_epochs,
            "val_rmse": val_rmse_values,
            "val_abs_rel_epochs": val_abs_rel_epochs,
            "val_abs_rel": val_abs_rel_values,
        }

        val_rmse_final = float(val_rmse_values[-1]) if val_rmse_values else None
        val_abs_rel_final = float(val_abs_rel_values[-1]) if val_abs_rel_values else None

        rows.append(
            {
                "method": method,
                "run": run_dir.name,
                "max_epoch": int(common_epochs[-1]),
                "train_final": float(train_common[-1]),
                "val_final": float(val_common[-1]),
                "generalization_gap_final": float(gap_common[-1]),
                "val_rmse_final": val_rmse_final,
                "val_abs_rel_final": val_abs_rel_final,
            }
        )

    if not curves:
        raise RuntimeError("No valid runs with epoch/train_loss and epoch/val_loss found.")

    train_curve_path = out_dir / "v2_training_error_lineplot.png"
    val_curve_path = out_dir / "v2_validation_error_lineplot.png"
    gap_curve_path = out_dir / "v2_generalization_gap_lineplot.png"
    final_bar_path = out_dir / "v2_final_error_bar.png"

    plot_lines(
        curves,
        key="train_loss",
        ylabel="Training Error (epoch/train_loss)",
        title=f"{args.title_prefix} - Training Error vs Epoch",
        out_path=train_curve_path,
    )
    plot_lines(
        curves,
        key="val_loss",
        ylabel="Validation Error (epoch/val_loss)",
        title=f"{args.title_prefix} - Validation Error vs Epoch",
        out_path=val_curve_path,
    )
    plot_lines(
        curves,
        key="generalization_gap",
        ylabel="Generalization Gap (val - train)",
        title=f"{args.title_prefix} - Generalization Gap vs Epoch",
        out_path=gap_curve_path,
    )
    plot_final_bar(
        curves,
        out_path=final_bar_path,
        title=f"{args.title_prefix} - Final Epoch Error",
    )

    summary = {
        "type": "fullscale_phase5_lineplots",
        "runs_json": str(runs_json),
        "methods": rows,
        "outputs": [
            str(train_curve_path),
            str(val_curve_path),
            str(gap_curve_path),
            str(final_bar_path),
        ],
    }

    metric_history = {
        "type": "fullscale_phase5_val_metric_history",
        "runs_json": str(runs_json),
        "history": val_metric_history,
    }

    summary_path = out_dir / "v2_fullscale_comparison_summary.json"
    metric_history_path = out_dir / "v2_val_metric_history.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    metric_history_path.write_text(json.dumps(metric_history, indent=2), encoding="utf-8")

    print("Saved figures:")
    for p in summary["outputs"]:
        print(f"  - {p}")
    print(f"Saved summary: {summary_path}")
    print(f"Saved val metric history: {metric_history_path}")


if __name__ == "__main__":
    main()
